"""add_production_ready_fields

Revision ID: 2c0123b6e2ab
Revises: 001
Create Date: 2026-05-28 16:15:31.478646+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c0123b6e2ab'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_files', sa.Column('processing_message', sa.String(length=255), nullable=True, comment='Current processing progress state description'))
    op.add_column('media_files', sa.Column('audio_duration_seconds', sa.Float(), nullable=True, comment='Duration of the audio file in seconds'))
    op.alter_column('media_files', 'id',
               existing_type=sa.UUID(),
               comment='Unique tracking identifier for the media asset',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('media_files', 'user_id',
               existing_type=sa.UUID(),
               comment='Owner user ID — references users.id',
               existing_nullable=False)
    op.alter_column('media_files', 'file_name',
               existing_type=sa.VARCHAR(length=500),
               comment='Original filename as provided by the client',
               existing_nullable=False)
    op.alter_column('media_files', 'storage_path',
               existing_type=sa.TEXT(),
               comment='Supabase Storage bucket path (e.g. user_id/uuid/filename.mp3)',
               existing_nullable=False)
    op.alter_column('media_files', 'file_size_bytes',
               existing_type=sa.BIGINT(),
               comment='Raw file size in bytes — used for subscription enforcement',
               existing_nullable=False)
    op.alter_column('media_files', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='file_status_enum'),
               comment='Processing lifecycle state',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::file_status_enum"))
    op.alter_column('media_files', 'error_message',
               existing_type=sa.TEXT(),
               comment="Failure reason stored when status transitions to 'failed'",
               existing_nullable=True)
    op.alter_column('media_files', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Upload initialization timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('media_files', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last state update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('summaries', sa.Column('generation_time_sec', sa.Float(), nullable=True, comment='Time in seconds taken to generate the summary'))
    op.alter_column('summaries', 'id',
               existing_type=sa.UUID(),
               comment='Unique summary row identifier',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('summaries', 'file_id',
               existing_type=sa.UUID(),
               comment='References the parent media asset',
               existing_nullable=False)
    op.alter_column('summaries', 'executive_summary',
               existing_type=sa.TEXT(),
               comment='3-5 paragraph narrative summary synthesized by Gemini',
               existing_nullable=False)
    op.alter_column('summaries', 'key_takeaways',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               comment='Structured insights: [{"point": "...", "category": "..."}]',
               existing_nullable=False)
    op.alter_column('summaries', 'action_items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               comment='Action items: [{"task": "...", "owner": "...", "priority": "..."}]',
               existing_nullable=False)
    op.alter_column('summaries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='LLM synthesis completion timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('summaries_file_id_key'), 'summaries', type_='unique')
    op.create_unique_constraint('uq_summaries_file_id', 'summaries', ['file_id'])
    op.add_column('transcripts', sa.Column('word_count', sa.Integer(), nullable=True, comment='Total word count in the transcript'))
    op.alter_column('transcripts', 'id',
               existing_type=sa.UUID(),
               comment='Unique transcript row identifier',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('transcripts', 'file_id',
               existing_type=sa.UUID(),
               comment='References the parent media asset',
               existing_nullable=False)
    op.alter_column('transcripts', 'raw_text',
               existing_type=sa.TEXT(),
               comment='Full concatenated transcription text',
               existing_nullable=False)
    op.alter_column('transcripts', 'segments',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Structured segments: [{start, end, text, speaker}]',
               existing_nullable=True)
    op.alter_column('transcripts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Worker completion timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('transcripts_file_id_key'), 'transcripts', type_='unique')
    op.create_unique_constraint('uq_transcripts_file_id', 'transcripts', ['file_id'])
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               comment='UUID matching Supabase auth.users.id',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment="User's authenticated email address",
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Account profile creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Account profile creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="User's authenticated email address",
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='UUID matching Supabase auth.users.id',
               existing_nullable=False)
    op.drop_constraint('uq_transcripts_file_id', 'transcripts', type_='unique')
    op.create_unique_constraint(op.f('transcripts_file_id_key'), 'transcripts', ['file_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('transcripts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Worker completion timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transcripts', 'segments',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Structured segments: [{start, end, text, speaker}]',
               existing_nullable=True)
    op.alter_column('transcripts', 'raw_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Full concatenated transcription text',
               existing_nullable=False)
    op.alter_column('transcripts', 'file_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='References the parent media asset',
               existing_nullable=False)
    op.alter_column('transcripts', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique transcript row identifier',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_column('transcripts', 'word_count')
    op.drop_constraint('uq_summaries_file_id', 'summaries', type_='unique')
    op.create_unique_constraint(op.f('summaries_file_id_key'), 'summaries', ['file_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('summaries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='LLM synthesis completion timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('summaries', 'action_items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               comment=None,
               existing_comment='Action items: [{"task": "...", "owner": "...", "priority": "..."}]',
               existing_nullable=False)
    op.alter_column('summaries', 'key_takeaways',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               comment=None,
               existing_comment='Structured insights: [{"point": "...", "category": "..."}]',
               existing_nullable=False)
    op.alter_column('summaries', 'executive_summary',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='3-5 paragraph narrative summary synthesized by Gemini',
               existing_nullable=False)
    op.alter_column('summaries', 'file_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='References the parent media asset',
               existing_nullable=False)
    op.alter_column('summaries', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique summary row identifier',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_column('summaries', 'generation_time_sec')
    op.alter_column('media_files', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last state update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('media_files', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Upload initialization timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('media_files', 'error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="Failure reason stored when status transitions to 'failed'",
               existing_nullable=True)
    op.alter_column('media_files', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='file_status_enum'),
               comment=None,
               existing_comment='Processing lifecycle state',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::file_status_enum"))
    op.alter_column('media_files', 'file_size_bytes',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Raw file size in bytes — used for subscription enforcement',
               existing_nullable=False)
    op.alter_column('media_files', 'storage_path',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Supabase Storage bucket path (e.g. user_id/uuid/filename.mp3)',
               existing_nullable=False)
    op.alter_column('media_files', 'file_name',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Original filename as provided by the client',
               existing_nullable=False)
    op.alter_column('media_files', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Owner user ID — references users.id',
               existing_nullable=False)
    op.alter_column('media_files', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique tracking identifier for the media asset',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_column('media_files', 'audio_duration_seconds')
    op.drop_column('media_files', 'processing_message')
    # ### end Alembic commands ###
